#ifndef KMEANSCLUSTERING_H__KMEANSCLUSTERING__LTILIB__LUA_PACKAGE__INCLUDED_
#define KMEANSCLUSTERING_H__KMEANSCLUSTERING__LTILIB__LUA_PACKAGE__INCLUDED_

namespace LTILib
{

	DECLARE_API(KMClustering, lti::kMeansClustering, LTILibPackageSngl);

} // namespace LTILib

#endif // !KMEANSCLUSTERING_H__KMEANSCLUSTERING__LTILIB__LUA_PACKAGE__INCLUDED_
