#ifndef LOADERS_H__TRAINERSMANAGER__INCLUDED_
#define LOADERS_H__TRAINERSMANAGER__INCLUDED_

static const StringA LOADER_PARAM_DIR_NAME = "dir";

#endif // !LOADERS_H__TRAINERSMANAGER__INCLUDED_
