#ifndef ENUMERATORS_H__HELPERS__MODEL__TRAINERSMANAGER__INCLUDED_
#define ENUMERATORS_H__HELPERS__MODEL__TRAINERSMANAGER__INCLUDED_



#endif // !ENUMERATORS_H__HELPERS__MODEL__TRAINERSMANAGER__INCLUDED_
