#ifndef SOFM2D_H__SOFM2D__LTILIB__LUA_PACKAGE__INCLUDED_
#define SOFM2D_H__SOFM2D__LTILIB__LUA_PACKAGE__INCLUDED_

namespace LTILib
{

	DECLARE_API(SOFM2D, lti::SOFM2D, LTILibPackageSngl);

} // namespace LTILib

#endif // !SOFM2D_H__SOFM2D__LTILIB__LUA_PACKAGE__INCLUDED_
