#ifndef COMPETITIVEAGGLOMERATION_H__COMPETITIVEAGGLOMERATION__LTILIB__LUA_PACKAGE__INCLUDED_
#define COMPETITIVEAGGLOMERATION_H__COMPETITIVEAGGLOMERATION__LTILIB__LUA_PACKAGE__INCLUDED_

namespace LTILib
{

	DECLARE_API(CompAgglom, lti::competitiveAgglomeration, LTILibPackageSngl);

} // namespace LTILib

#endif // !COMPETITIVEAGGLOMERATION_H__COMPETITIVEAGGLOMERATION__LTILIB__LUA_PACKAGE__INCLUDED_
