//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NeuroLab.rc
//
#define IDP_OLE_INIT_FAILED             100
#define IDD_ABOUTBOX                    100
#define IDD_NEUROLAB_FORM               101
#define IDC_POINTER_LINK                104
#define IDC_POINTER_COPY                105
#define IDC_NODROP                      106
#define IDC_POINTER_LINK_ACCEPTED       107
#define IDR_MAINFRAME                   128
#define IDR_NeuroLabTYPE                129
#define IDR_BUILDERPOPUP                130
#define IDD_NEURONPROPERTIESDLG         132
#define IDD_NEURONFUNCTIONSDLG          133
#define IDD_CONFIGUREFUNCDLG            134
#define IDD_SELECTFUNCTIONDLG           135
#define IDD_NEURONQUICKINFODLG          136
#define IDD_LOAD_STAT_DLG               140
#define IDD_NO_PLUGIN_BAR_TO_SHOW_DLG   143
#define IDD_BUILDER_PROPERTIES          144
#define IDI_UPARROW                     147
#define IDI_DOWNARROW                   148
#define IDB_APP_LOGO                    152
#define IDD_TRAINING_NETWORK_DLG        153
#define IDD_NETWORK_VERIFICATION_DLG    154
#define IDD_TRAINER_TOOL_DLG            155
#define IDD_TRAINING_PROPERTIES_DLG     156
#define IDI_SAVE                        159
#define IDI_TB_MAIN_NEWFILE             161
#define IDI_TB_MAIN_OPENFILE            162
#define IDI_TB_MAIN_SAVEFILE            163
#define IDI_ICON2                       164
#define IDI_TB_MAIN_ABOUT               164
#define IDC_BUTTON1                     1000
#define IDC_REMOVEDENDRITE              1000
#define IDC_FUNCCONFIGURE               1000
#define IDC_VERIFY                      1000
#define IDC_CONFIGURE_TRAINER           1000
#define IDC_ELEMENTSTREE                1001
#define IDC_AXONSTREE                   1006
#define IDC_PROPTAB                     1006
#define IDC_NURONID                     1007
#define IDC_ELTITLE                     1008
#define IDC_DENDRITEWEIGHT              1009
#define IDC_TREE1                       1011
#define IDC_DENDRTREE                   1011
#define IDC_FUNCTIONSTREE               1011
#define IDC_FNTREE                      1011
#define IDC_REMOVEAXON                  1013
#define IDC_TOOLSBARTITLE               1014
#define IDC_BULDERINFO                  1016
#define IDC_BUILDERINFO                 1016
#define IDC_LIST1                       1017
#define IDC_FUNCTIONEXPRESSION          1020
#define IDC_FUNCTIONNAME                1022
#define IDC_SELECTFUNCTION              1023
#define IDC_FUNCEXPRESSION              1025
#define IDC_DENDRCOUNT                  1026
#define IDC_AXONSCOUNT                  1027
#define IDC_VERIFLOG                    1028
#define IDC_ELEMENT_ID                  1028
#define IDC_AUTOCORRECT                 1029
#define IDC_VERIFTYPE                   1030
#define IDC_BUTTON3                     1031
#define IDC_SHOWDETAILS                 1032
#define IDC_LOGLIST                     1034
#define IDC_INFOHEADERCONTROL           1035
#define IDC_LOAD_STATE_STRING           1036
#define IDC_SHOW_GRID                   1040
#define IDC_ATTACH_TO_GRID              1042
#define IDC_GRID_RANGE                  1043
#define IDC_GRID_RANGE_TITLE            1044
#define IDC_DOWN_MOVE_DENDRITE          1045
#define IDC_UP_MOVE_DENDRITE            1046
#define IDC_FUNC_SCALE                  1046
#define IDC_DOWN_MOVE_AXON              1047
#define IDC_UP_MOVE_AXON                1048
#define IDC_DENDRITE_COUNT              1049
#define IDC_AXON_COUNT                  1050
#define IDC_TRAINING_METHODS_TREE       1050
#define IDC_CONFIGURE_METHOD            1051
#define IDC_LOAD_DATA                   1052
#define IDC_START_TRAINING              1054
#define IDC_VERIFICATION_RESULTS        1055
#define IDC_DATA_STATUS                 1056
#define IDC_INPUTS_COUNT                1057
#define IDC_INPUT_SYMBOL_LENGTH         1058
#define IDC_DATA_DETAILS                1059
#define IDC_OUTPUTS_COUNT               1060
#define IDC_OUTPUT_SYMBOL_LENGTH        1061
#define IDC_STOP_TRAINING               1061
#define IDC_SAVE_TRAINING_LOG           1062
#define IDC_TRAINING_PROGRESS           1063
#define IDC_TRAINER_NAME                1064
#define IDC_TRAINING_EVENTS_LOG         1065
#define IDC_PROCESS_TRAINING            1066
#define IDC_PAUSE_TRAINING              1067
#define IDC_TRAINING_PROPERTIES         1068
#define IDC_TRAINER_VERSION             1069
#define IDC_USE_NETWORK_MAP             1069
#define IDC_CURRENT_PERCENT             1070
#define IDC_ELEMENT_TYPE                1071
#define IDC_ELEMENT_NAME                1072
#define IDC_SYSTEM_NAME                 1073
#define IDC_REQUIRES_DATA               1074
#define IDC_DATA_LENGTH                 1075
#define IDC_FUNCK_VIEW_SCALE            1078
#define IDC_FUNC_VIEW_SCALE             1078
#define IDC_ERRORS_COUNT                1079
#define IDC_WARNINGS_COUNT              1080
#define IDR_BUILDERCTRL                 10001
#define ID_CUST_FILE_OPEN               20776
#define ID_CUST_FILE_SAVE               20777
#define ID_CUST_FILE_SAVE_AS            20778
#define ID_CUST_FILE_NEW                20779
#define ID_PROPERTIES                   32772
#define ID_CELLBODY_PROPERTIES          32774
#define ID_CELLBODY_LINKTO              32775
#define ID_FILE_EXPORT                  32780
#define ID_EXPORT_NETWORK               32781
#define ID_Menu                         32782
#define ID_FILE_ASSDF                   32783
#define ID_CELLBODY_ADDDENDRITE         32784
#define ID_CELLBODY_ADDAXON             32785
#define ID_BUILDERINFOPANEL_CLEARAREA   32788
#define ID_BUILDERINFOPANEL_EXPORT      32789
#define ID_CELLBODY_REMOVE              32792
#define ID_BUILDER_PROPERTIES           32793
#define ID_LAYER_PROPERTIES             32794
#define ID_LAYER_CONNECTIONSORDER       32795
#define ID_TOOLS_DATACREATOR            32797
#define ID_USER_GUIDE                   32798
#define ID_BUILDER_SELECTALL            32799
#define ID_BUILDER_EXPORT_              32800
#define ID_EXPORT_NETWORKANDLIBS        32801
#define ID_TOOLS_NETWORKEXPORRTER       32804
#define IDC_BUILDER_INFO                50001
#define IDC_TOOLS_INFO                  50002
#define ID_FUNCTIONSHOWCTRL             50003
#define ID_QUICKFUNCTIONSHOWCTRL        50004
#define ID_VERIFICATIONRESULTS          50005
#define IDC_PLUGINSPANEL_INFO           50006
#define IDC_QUICKVIEW_INFO              50007
#define ID_TOOLTIP_NBINFO               60000
#define ID_TOOLTIP_NBINFO_RIGHT         60001
#define ID_TOOLTIP_TBINFO               60002
#define ID_TOOLTIP_TBINFO_RIGHT         60003

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        167
#define _APS_NEXT_COMMAND_VALUE         32805
#define _APS_NEXT_CONTROL_VALUE         1081
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
