#ifndef GLOBAL_H__SCRIPTSMACHINE__INCLUDED_
#define GLOBAL_H__SCRIPTSMACHINE__INCLUDED_

namespace ScriptsMachine
{

	DECLARE_EXTENSION(Global);

}

#endif // !GLOBAL_H__SCRIPTSMACHINE__INCLUDED_
