#ifndef ADAPTIVEKMEANS_H__ADAPTIVEKMEANS__LTILIB__LUA_PACKAGE__INCLUDED_
#define ADAPTIVEKMEANS_H__ADAPTIVEKMEANS__LTILIB__LUA_PACKAGE__INCLUDED_

namespace LTILib
{

	DECLARE_API(AdaptiveKM, lti::adaptiveKMeans, LTILibPackageSngl);

} // namespace LTILib

#endif // !ADAPTIVEKMEANS_H__ADAPTIVEKMEANS__LTILIB__LUA_PACKAGE__INCLUDED_
