#ifndef FUZZYCMEANS_H__FUZZYCMEANS__LTILIB__LUA_PACKAGE__INCLUDED_
#define FUZZYCMEANS_H__FUZZYCMEANS__LTILIB__LUA_PACKAGE__INCLUDED_

namespace LTILib
{

	DECLARE_API(FuzzyCM, lti::fuzzyCMeans, LTILibPackageSngl);

} // namespace LTILib

#endif // !FUZZYCMEANS_H__FUZZYCMEANS__LTILIB__LUA_PACKAGE__INCLUDED_
