#ifndef SCRIPTLOCALS_H__SCRIPTSMACHINE__INCLUDED_
#define SCRIPTLOCALS_H__SCRIPTSMACHINE__INCLUDED_

namespace ScriptsMachine
{

	DECLARE_EXTENSION(ScriptLocals);

}

#endif // !SCRIPTLOCALS_H__SCRIPTSMACHINE__INCLUDED_
