//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DataCreator.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDM_USERGUIDE                   0x0020
#define IDM_SDKDOC						0x0030
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DATACREATOR_DIALOG          102
#define IDS_SDKDOK                      102
#define IDS_USERGUIDE                   103
#define IDC_POINTER_COPY                105
#define IDC_NODROP                      106
#define IDR_MAINFRAME                   128
#define IDD_DATA_FILES                  129
#define IDI_UPARROW                     130
#define IDI_DOWNARROW                   131
#define IDD_NEW_FILE_DLG                132
#define IDI_CTRL_PROP                   133
#define IDI_CTRL_EDITOR                 137
#define IDD_DATA_COLLECTIONS            138
#define IDD_NEW_COLLECTION_DLG          142
#define IDD_NEW_GROUP_DLG               143
#define IDD_DC_TO_DF_DLG                145
#define IDD_NEW_CONVERTER_DLG           146
#define IDD_NEW_CONVERTER_ITEM_DLG      147
#define IDD_SELECT_DATA_SYMBOL_DLG      148
#define IDD_SELECT_COLLECTION_GROUP_DLG 149
#define IDD_EXPORTING_COLLECTION_DLG    150
#define IDC_TAB1                        1000
#define IDC_MAIN_TAB                    1000
#define IDC_PANEL_BAR                   1001
#define IDC_BUTTON1                     1002
#define IDC_NEW                         1002
#define IDC_INFOHEADERCONTROL           1002
#define IDC_DATA_COLLECTION_DETAILS     1002
#define IDC_DATA_COLLECTION_LOAD        1002
#define IDC_SELECT_GROUP_NAME           1002
#define IDC_BUTTON2                     1003
#define IDC_LOAD                        1003
#define IDC_DETAILS_DATA_COLLECTION     1003
#define IDC_SELECT_SYMBOL_INDEX         1003
#define IDC_UP_SYMBOL                   1003
#define IDC_BROWSE                      1003
#define IDC_BUTTON3                     1004
#define IDC_SAVE                        1004
#define IDC_DATA_FILE_DETAILS           1004
#define IDC_DATA_FILE_LOAD              1004
#define IDC_DOWN_SYMBOL                 1004
#define IDC_CONVERT                     1004
#define IDC_INPUT_SYMBOL_BUILDER        1005
#define IDC_DETEILS_DATA_FILE           1005
#define IDC_BUTTON4                     1005
#define IDC_SYMBOL_PROPERTIES           1005
#define IDC_UP_LIST_INPUTS              1006
#define IDC_DOWN_LIST_INPUTS            1007
#define IDC_BUTTON8                     1010
#define IDC_ADD_INPUT_SYMBOL            1010
#define IDC_LOAD_PROJECT                1010
#define IDC_BUTTON9                     1011
#define IDC_REMOVE_INPUT_SYMBOL         1011
#define IDC_SAVE_PROJECT                1011
#define IDC_BUTTON10                    1012
#define IDC_SET_INPUT_MARKER            1012
#define IDC_EXPORT_PROJECT              1012
#define IDC_EDIT2                       1013
#define IDC_FILE_NAME                   1013
#define IDC_NEW_PROJECT                 1013
#define IDC_PROJECT_NAME                1013
#define IDC_DATA_FILE_INPUT_DIMENSION   1013
#define IDC_INPUT_LENGTH                1014
#define IDC_Close_PROJECT2              1014
#define IDC_CLOSE_PROJECT               1014
#define IDC_OUTPUT_LENGTH               1015
#define IDC_MODIFIED_STATE              1016
#define IDC_INPUT_NUMBER                1017
#define IDC_OUTPUT_NUMBER               1018
#define IDC_TOTAL_INPUTS                1019
#define IDC_TOTAL_OUTPUTS               1020
#define IDC_INPUT_MARKER                1021
#define IDC_OUTPUT_MARKER               1022
#define IDC_OUTPUT_SYMBOL_BUILDER       1023
#define IDC_UP_LIST_OUTPUTS             1024
#define IDC_DOWN_LIST_OUTPUTS           1025
#define IDC_BUTTON13                    1026
#define IDC_ADD_OUTPUT_SYMBOL           1026
#define IDC_BUTTON14                    1027
#define IDC_REMOVE_OUTPUT_SYMBOL        1027
#define IDC_BUTTON15                    1028
#define IDC_SET_OUTPUT_MARKER           1028
#define IDC_INPUT_CTRL_PROP             1029
#define IDC_OUTPUT_CTRL_PROP            1030
#define IDC_MARKER_VALUE                1034
#define IDC_SAVE_AS                     1035
#define IDC_XDIMENSION                  1036
#define IDC_YDIMENSION                  1037
#define IDC_DATA_LENGTH                 1038
#define IDC_INPUT_CTRL_EDITOR           1039
#define IDC_OUTPUT_CTRL_EDITOR          1040
#define IDC_COLLECTION_TREE             1042
#define IDC_COLLECTION_PROPERTIES       1043
#define IDC_EDIT1                       1050
#define IDC_COLLECTION_NAME             1050
#define IDC_PROJ_NAME                   1050
#define IDC_COLL_GROUP_NAME             1050
#define IDC_DESTINATION_FILE_NAME       1050
#define IDC_SYMBOL_INDEX                1051
#define IDC_CUSTOM1                     1052
#define IDC_GROUP_NAME                  1053
#define IDC_PROJECT_CONTENT             1055
#define IDC_ADD_ENTRY                   1056
#define IDC_EDIT_ENTRY                  1057
#define IDC_REMOVE_ENTRY                1058
#define IDC_DATA_COLLECTION_NAME        1059
#define IDC_DATA_FILE_OUTPUTS           1060
#define IDC_DATA_COLLECTION_FILE_NAME   1061
#define IDC_DATA_FILE_FILE_NAME         1063
#define IDC_SYMBOLS_COUNT               1063
#define IDC_DATA_FILE_OUTPUTS_COUNT     1064
#define IDC_SYMBOL_DIMENSION            1064
#define IDC_COLLECTION_GROUPS_TREE      1065
#define IDC_DATA_ITEMS                  1066
#define IDC_SUBGROUPS                   1067
#define IDC_LIST1                       1068
#define IDC_TITLE_PANEL_BAR             10000
#define IDR_PROXYOBJ                    20000
#define IDC_SYMBOL_CTRL                 20001
#define ID_123_12312                    32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1069
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
