#ifndef THREADING_H__SCRIPTSMACHINE__INCLUDED_
#define THREADING_H__SCRIPTSMACHINE__INCLUDED_

namespace ScriptsMachine
{

	DECLARE_EXTENSION(Threading);

}

#endif // !THREADING_H__SCRIPTSMACHINE__INCLUDED_
